### ISSUE TITLE
custom deps trying to run setup for  - zha-quirks==0.0.85 i get s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by ernstmosch** [home-assistant/addons-development#91]
Hello Community im not sure if i shoul post my issue overall - and imm defenitly not sure if this is the right place here.

But i want to give it a try.

My Setup:

Home Assistant 2022.11.2
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest

Im using - or to be correct - i have been using - the custom deps addon to install the zha-quirks librariy.

Config
pypi:
  - zha-quirks==0.0.85
apk: []

I did that for quite some versions.

But with since an update of the operatiing system i guess i get an "s6-overlay-suexec: fatal: can only run as pid 1" error when i try to start the addon.

Please tell me if im in the right spot here or if im just bothering everybody.

Greez, Ernst

**Comment by Visolo** [comment]
I have the same issue.

Home assistant supervised.

All versións in the last.

Install addon with this config:
pypi:
  - wiringpi
apk: []

Addons don´t start with this log:
s6-overlay-suexec: fatal: can only run as pid 1

**Comment by Visolo** [comment]
There are a few bugs in the actual code. I have corrected them and made a pull request.

**Comment by ernstmosch** [comment]
Hi Visolo,

Home Assistant 2022.12.1
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221208.0 - latest

And im Still getting the:
s6-overlay-suexec: fatal: can only run as pid 1

Sorry

**Comment by Visolo** [comment]
The pull request is waiting for approval and merge. We only can wait for it.

**Comment by leyzix** [comment]
I have the same problem. Waiting for resolving issue.

**Comment by Bajek** [comment]
Hey,

Any chance to fix the issue soon?

Thanks
B.

**Comment by awm1** [comment]
> The pull request is waiting for approval and merge. We only can wait for it.

I think you should re-open your pull request, report of its existence for maintainers of this repository could have been blocked.

**Comment by Visolo** [comment]
Since it seems that they are not going to merge my pull request, I have compiled my version of the addon and published it in my repository.
Feel free to try it.
https://github.com/Visolo/ha-addons

**Comment by awm1** [comment]
Thank you, it solved my issue - finally, I don't have to switch
tuya-iot-python-sdk to my fork every time I update my HA instance. Hope
your pull request will be reviewed soon.

ne 8. 1. 2023 v 1:20 odesílatel David Pose ***@***.***>
napsal:

**Comment by agners** [comment]
Fixed with https://github.com/home-assistant/addons-development/pull/97.
